`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 2021/12/30 16:21:20
// Design Name: 
// Module Name: AFNS_Adder_13
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////

// Generated by cac_main.ns_tools.verilog_generate_code_AFNSAdder(), version: 2022010100.
`include "Header_AdaptiveFNS.vh"
module AFNS_Adder_13(
    input wire flag,
    input wire [`AFNS_ADDER_OUTA_BLEN_12 - 1 : 0] in_a,
    input wire [`AFNS_ADDER_OUTB_BLEN_12 - 1 : 0] in_b,
    output wire [`AFNS_ADDER_OUTA_BLEN_13 - 1 : 0] out_a,
    output wire [`AFNS_ADDER_OUTB_BLEN_13 - 1 : 0] out_b
     );
    
    wire [`AFNS_ADDER_OUTA_BLEN_13 - 1 : 0] sum;
    
    assign sum[`AFNS_ADDER_OUTA_BLEN_13 - 1 : 0] = in_a[`AFNS_ADDER_OUTA_BLEN_12 - 1 : 0] + in_b[`AFNS_ADDER_OUTB_BLEN_12 - 1 : 0];
    assign out_a[`AFNS_ADDER_OUTA_BLEN_13 - 1 : 0] = (flag == 1'b0) ? (sum[`AFNS_ADDER_OUTA_BLEN_13 - 1 : 0]) : (in_a[`AFNS_ADDER_OUTA_BLEN_12 - 1 : 0]);
    assign out_b[`AFNS_ADDER_OUTB_BLEN_13 - 1 : 0] = (flag == 1'b0) ? (in_a[`AFNS_ADDER_OUTA_BLEN_12 - 1 : 0]) : (in_b[`AFNS_ADDER_OUTB_BLEN_12 - 1 : 0]);
    
endmodule
// End
