`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 2022/01/07 21:30:37
// Design Name: 
// Module Name: AFNS_CascadedAdders_N07
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


//E:\Workspace\Repositories\Research\TSV\TSV-DyMFNS\Python\DyMFNS_CAC\venv\Scripts\python.exe E:/Workspace/Repositories/Research/TSV/TSV-DyMFNS/Python/DyMFNS_CAC/cac_main/verilog_generation_tools.py
// Generated by cac_main.verilog_generation_tools. Version: 2022.01.07.00
`include "Header_AdaptiveFNS.vh"
module AFNS_CascadedAdders_N07(
    // flags
    input wire [1:7] flags,
    // output ports
    output wire out_a_01,
    output wire out_b_01,
    output wire [`AFNS_ADDER_OUTA_BLEN_2 - 1 : 0] out_a_02,
    output wire [`AFNS_ADDER_OUTB_BLEN_2 - 1 : 0] out_b_02,
    output wire [`AFNS_ADDER_OUTA_BLEN_3 - 1 : 0] out_a_03,
    output wire [`AFNS_ADDER_OUTB_BLEN_3 - 1 : 0] out_b_03,
    output wire [`AFNS_ADDER_OUTA_BLEN_4 - 1 : 0] out_a_04,
    output wire [`AFNS_ADDER_OUTB_BLEN_4 - 1 : 0] out_b_04,
    output wire [`AFNS_ADDER_OUTA_BLEN_5 - 1 : 0] out_a_05,
    output wire [`AFNS_ADDER_OUTB_BLEN_5 - 1 : 0] out_b_05,
    output wire [`AFNS_ADDER_OUTA_BLEN_6 - 1 : 0] out_a_06,
    output wire [`AFNS_ADDER_OUTB_BLEN_6 - 1 : 0] out_b_06,
    output wire [`AFNS_ADDER_OUTA_BLEN_7 - 1 : 0] out_a_07,
    output wire [`AFNS_ADDER_OUTB_BLEN_7 - 1 : 0] out_b_07
    );
    
//////////////////////////////////////////////////////////////////////////////////
// Design
//////////////////////////////////////////////////////////////////////////////////
    
    // Adder 1
    AFNS_Adder_01 adder01(.flag(flags[1]), .out_a(out_a_01), .out_b(out_b_01));
    
    // Adder 2
    AFNS_Adder_02 adder02( 
                            .flag(flags[2]),
                            .in_a(out_a_01),
                            .in_b(out_b_01),
                            .out_a(out_a_02),
                            .out_b(out_b_02)
                            );
    
    // Adder 3
    AFNS_Adder_03 adder03( 
                            .flag(flags[3]),
                            .in_a(out_a_02),
                            .in_b(out_b_02),
                            .out_a(out_a_03),
                            .out_b(out_b_03)
                            );
    
    // Adder 4
    AFNS_Adder_04 adder04( 
                            .flag(flags[4]),
                            .in_a(out_a_03),
                            .in_b(out_b_03),
                            .out_a(out_a_04),
                            .out_b(out_b_04)
                            );
    
    // Adder 5
    AFNS_Adder_05 adder05( 
                            .flag(flags[5]),
                            .in_a(out_a_04),
                            .in_b(out_b_04),
                            .out_a(out_a_05),
                            .out_b(out_b_05)
                            );
    
    // Adder 6
    AFNS_Adder_06 adder06( 
                            .flag(flags[6]),
                            .in_a(out_a_05),
                            .in_b(out_b_05),
                            .out_a(out_a_06),
                            .out_b(out_b_06)
                            );
    
    // Adder 7
    AFNS_Adder_07 adder07( 
                            .flag(flags[7]),
                            .in_a(out_a_06),
                            .in_b(out_b_06),
                            .out_a(out_a_07),
                            .out_b(out_b_07)
                            );
    
endmodule

//Process finished with exit code 0

