`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 2022/01/08 15:35:42
// Design Name: 
// Module Name: DyMFNS_CascadedAdders_N04
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


//E:\Workspace\Repositories\Research\TSV\TSV-DyMFNS\Python\DyMFNS_CAC\venv\Scripts\python.exe E:/Workspace/Repositories/Research/TSV/TSV-DyMFNS/Python/DyMFNS_CAC/cac_main/verilog_generation_tools.py
// Generated by cac_main.verilog_generation_tools. Version: 2022.01.08.00
`include "Header_DyMFNS.vh"
module DyMFNS_CascadedAdders_N04(
    // flags
    input wire [1:4] flags,
    // Output ports
    input wire out_a_01,
    input wire out_b_01,
    input wire [`DYMFNS_ADDER_OUTA_BLEN_2 - 1 : 0] out_a_02,
    input wire [`DYMFNS_ADDER_OUTB_BLEN_2 - 1 : 0] out_b_02,
    input wire [`DYMFNS_ADDER_OUTA_BLEN_3 - 1 : 0] out_a_03,
    input wire [`DYMFNS_ADDER_OUTB_BLEN_3 - 1 : 0] out_b_03,
    input wire [`DYMFNS_ADDER_OUTA_BLEN_4 - 1 : 0] out_a_04,
    input wire [`DYMFNS_ADDER_OUTB_BLEN_4 - 1 : 0] out_b_04
    );
    
    // flags
    wire [4:2] flags_notlsb; 
    
//////////////////////////////////////////////////////////////////////////////////
// Design
//////////////////////////////////////////////////////////////////////////////////
    
    DyMFNS_Adder_01 adder01(.flag(flags[1]), .flag_notlsb_out(flags_notlsb[2]), .out_a(out_a_01), .out_b(out_b_01));
    
    // Adder 2
    DyMFNS_Adder_02 adder02(.flag_left(flags[1]), 
                            .flag(flags[2]),
                            .flag_right(flags[3]),
                            .flag_notlsb_in(flags_notlsb[2]), 
                            .in_a(out_a_01),
                            .in_b(out_b_01),
                            .flag_notlsb_out(flags_notlsb[3]),
                            .out_a(out_a_02),
                            .out_b(out_b_02)
                            );
    
    // Adder 3
    DyMFNS_Adder_03 adder03(.flag_left(flags[2]), 
                            .flag(flags[3]),
                            .flag_right(flags[4]),
                            .flag_notlsb_in(flags_notlsb[3]), 
                            .in_a(out_a_02),
                            .in_b(out_b_02),
                            .flag_notlsb_out(flags_notlsb[4]),
                            .out_a(out_a_03),
                            .out_b(out_b_03)
                            );
    
    // Adder 4
    DyMFNS_Adder_04 adder04(.flag_left(flags[3]), 
                            .flag(flags[4]),
                            .flag_right(1'b1),
                            .flag_notlsb_in(flags_notlsb[4]), 
                            .in_a(out_a_03),
                            .in_b(out_b_03),
                            .flag_notlsb_out(),
                            .out_a(out_a_04),
                            .out_b(out_b_04)
                            );
    
endmodule

//Process finished with exit code 0

